### ISSUE TITLE
Non-ASCII characters in a filename

### ISSUE THREAD

**Issue by Marina-Blmz** [pipitone/qbatch#208]
I ran into the following error when submitting jobs with qbatch: :

```5 atlases, 21 templates, 173 subjects found
running 105 commands after stage NONE*
qbatch: warning: Dependencies specified but no running jobs found
Submitted batch job 3219693
running 173 commands after stage mb_templatelib_2020-05-13T15-37-30*
Traceback (most recent call last):
  File "/scinet/niagara/software/2018a/opt/base/qbatch/2.1.5/bin/qbatch", line 9, in <module>
    load_entry_point('qbatch==2.1.5', 'console_scripts', 'qbatch')()
  File "/scinet/niagara/software/2018a/opt/base/qbatch/2.1.5/lib/python2.7/site-packages/qbatch/qbatch.py", line 727, in qbatchParser
    qbatchDriver(**vars(args))
  File "/scinet/niagara/software/2018a/opt/base/qbatch/2.1.5/lib/python2.7/site-packages/qbatch/qbatch.py", line 517, in qbatchDriver
    ''.join(task_list),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 90: ordinal not in range(128) 
….
```
and the warning message in logs was: “/var/spool/slurm/slurmd/job3219808/slurm_script: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory”.
The cause of this problem lies in non-ASCII characters in the filenames, for example, one of files was named: NOLD_sT1W_3D_TFE_v_N_İ_AKTAŞ.convert.n4correct.cutneckapplyautocrop.beastextract.

**Comment by gdevenyi** [comment]
Fixed in v2.2.1
